# pylint: skip-file
# Generated by Django 3.2.15 on 2022-09-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging', '0004_outgoingmessage_message_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMessageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='outgoing_message_media')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='simple_messaging.outgoingmessage')),
            ],
        ),
    ]
