# pylint: skip-file
# Generated by Django 3.2.16 on 2023-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging', '0005_outgoingmessagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='lookup_key',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='lookup_key',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
