# pylint: skip-file
# Generated by Django 3.2.25 on 2024-11-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging', '0006_auto_20230201_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256)),
                ('blocked', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
