# pylint: skip-file
# Generated by Django 5.2.12 on 2026-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging', '0007_blockedsender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='message',
            field=models.TextField(max_length=1048576),
        ),
    ]
