# pylint: skip-file
# Generated by Django 3.2.25 on 2026-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging', '0008_alter_outgoingmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomposedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1048576)),
                ('label', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
