# pylint: skip-file

# Generated by Django 3.2.25 on 2026-08-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_messaging', '0010_outgoingmessage_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='labels',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
    ]
